### ISSUE TITLE
Startup error with bard token ___SECURE_1PSID 

### ISSUE THREAD

**Issue by Murat1Na** [FuseFairy/DiscordBot-BardGPT#12]
I get this error im sure abt the  ___SECURE_1PSID is there
 
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/container/cogs/event.py", line 15, in <module>
    chatbot = MentionChatbot()
  File "/home/container/src/mention_chatbot.py", line 15, in __init__
    self.chatbot = Bard(token=os.getenv("___SECURE_1PSID"))
  File "/home/container/.local/lib/python3.10/site-packages/bardapi/core.py", line 78, in __init__
    self.SNlM0e = self._get_snim0e()
  File "/home/container/.local/lib/python3.10/site-packages/bardapi/core.py", line 154, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/bot.py", line 46, in on_ready
    await bot.load_extension(f'cogs.{Filename[:-3]}')
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 938, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.event' raised an error: Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

**Comment by coyottetv** [comment]
hi test have the token via private browsing

**Comment by Murat1Na** [comment]
> hi test have the token via private browsing

sorry, I didn't get it wdym

**Comment by FuseFairy** [comment]
private browsing

![image](https://github.com/FuseFairy/DiscordBot-BardGPT/assets/78064680/c1b35ad4-5f9f-41ba-afd7-918fb8ac6a13)

**Comment by Murat1Na** [comment]
Thanks
