### ISSUE TITLE
problem limit 2000 characters

### ISSUE THREAD

**Issue by coyottetv** [FuseFairy/DiscordBot-BardGPT#13]
Error: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.

when the bot speaks and the limit of 2000 characters is exceeded, the bot tells me that

a solution ?

**Comment by coyottetv** [comment]
here is console error Error: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
Traceback (most recent call last):
  File "/home/DiscordBot-BardGPT/src/response.py", line 93, in send_message
    await interaction.channel.send(text)
  File "/usr/local/lib/python3.10/dist-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.

**Comment by FuseFairy** [comment]
in src/response.py line 45~52, change like this and try again.

```python
        # Discord limit about 2000 characters for a message
        while len(response) > 1500:
            temp = response[:1500]
            response = response[1500:]
            if isinstance(interaction, discord.Interaction):
                await interaction.followup.send(temp)
            elif isinstance(interaction, discord.message.Message):
                await interaction.channel.send(temp)
```

**Comment by coyottetv** [comment]
I just tested it, still the same

**Comment by FuseFairy** [comment]
change src/response.py like this

```python
import asyncio
import re
from bardapi import Bard
from src import log

logger = log.setup_logger(__name__)

async def chatbot_ask(chatbot: Bard, message: str, image=None):
    loop = asyncio.get_running_loop()
    if image:
        result = await loop.run_in_executor(None, chatbot.ask_about_image, message, image)
    else:
        result = await loop.run_in_executor(None, chatbot.get_answer, message)
    return result

async def send_message(chatbot: Bard, interaction, user_message: str, image=None):
    reply = ''
    text = ''
    ask = ''
    images_embed = []
    more_images_links = []
    more_images_embed = ''
    if isinstance(interaction, discord.Interaction):
        await interaction.response.defer(ephemeral=False, thinking=True)
    elif isinstance(interaction, discord.message.Message):
        await interaction.channel.typing()
    try:
        if image:
            reply = await chatbot_ask(chatbot, user_message, image)
        else:
            reply = await chatbot_ask(chatbot, user_message)

        # Get reply text
        text = f"{reply['content']}"
        text = re.sub(r'\[Image of[^\]]*?\].*?\n?', '', text)
        text = re.sub(r'\[\d+\s+Images\s+of\s+[^\]]*\]', '', text)

        # Set the final message
        if isinstance(interaction, discord.Interaction):
            user_message = user_message.replace("\n", "")
            ask = f"> **{user_message}** - <@{str(interaction.user.id)}>\n\n"
        response = f"{ask}{text}"

        # Discord limit about 2000 characters for a message
        while len(response) > 2000:
            temp = response[:2000]
            response = response[2000:]
            if isinstance(interaction, discord.Interaction):
                await interaction.followup.send(temp)
            elif isinstance(interaction, discord.message.Message):
                await interaction.channel.send(temp)

        # Get the image, if available
        if (len(reply["images"]) > 0 and reply["images"][0] != ""):
            i = 1
            count = 0

            for image_link in reply["images"]:
                if len(images_embed) < 10:
                    images_embed.append(discord.Embed(url=f"https://bard.google.com/{i}").set_image(url=image_link))
                    count += 1
                    if count == 4:
                        i += 1
                        count = 0
                else:
                    more_images_links.append(image_link)
            if len(more_images_links) > 0:
                link_text = "\n\n".join(more_images_links)
                if len(link_text) < 4096:
                    more_images_embed = discord.Embed(title= "More Links", description=link_text)

        if len(images_embed) > 0 and len(more_images_embed) > 0:
            if isinstance(interaction, discord.Interaction):
                await interaction.followup.send(response, embeds=images_embed, wait=True)
                await interaction.followup.send(embed=more_images_embed, wait=True)
            elif isinstance(interaction, discord.message.Message):
                await interaction.channel.send(response, embeds=images_embed)
                await interaction.channel.send(embed=more_images_embed)
        elif len(images_embed) > 0:
            if isinstance(interaction, discord.Interaction):
                await interaction.followup.send(response, embeds=images_embed, wait=True)
            elif isinstance(interaction, discord.message.Message):
                await interaction.channel.send(response, embeds=images_embed)
        else:
            if isinstance(interaction, discord.Interaction):
                await interaction.followup.send(response, wait=True)
            elif isinstance(interaction, discord.message.Message):
                await interaction.channel.send(response)
    except Exception as e:
            if isinstance(interaction, discord.Interaction):
                await interaction.followup.send(f">>> **ERROR: {e}**")
            elif isinstance(interaction, discord.message.Message):
                await interaction.channel.send(f">>> **ERROR: {e}**")
            logger.exception(f"Error: {e}")
```

**Comment by coyottetv** [comment]
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/DiscordBot-BardGPT/cogs/event.py", line 46, in on_message
    await chatbot.send_message(message, content)
  File "/home/DiscordBot-BardGPT/src/mention_chatbot.py", line 22, in send_message
    await send_message(self.chatbot, message, content)
  File "/home/DiscordBot-BardGPT/src/response.py", line 23, in send_message
    if isinstance(interaction, discord.Interaction):
NameError: name 'discord' is not defined

**Comment by coyottetv** [comment]
it's okay I added it  import discord 

thank you it works great
