### ISSUE TITLE
Bot Broken

### ISSUE THREAD

**Issue by darnells68** [FuseFairy/DiscordBot-BardGPT#15]
I just tried this bot, added all the env data but its simply is not working I think its broken.

Traceback (most recent call last):
  File "c:\Users\darne\Desktop\DiscordBot-BardGPT\myenv\lib\site-packages\discord\ext\commands\bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\darne\Desktop\DiscordBot-BardGPT\cogs\event.py", line 15, in <module>
    chatbot = MentionChatbot()
  File "C:\Users\darne\Desktop\DiscordBot-BardGPT\src\mention_chatbot.py", line 15, in __init__
    self.chatbot = Bard(token=os.getenv("___SECURE_1PSID"))
  File "c:\Users\darne\Desktop\DiscordBot-BardGPT\myenv\lib\site-packages\bardapi\core.py", line 78, in __init__
    self.SNlM0e = self._get_snim0e()
  File "c:\Users\darne\Desktop\DiscordBot-BardGPT\myenv\lib\site-packages\bardapi\core.py", line 154, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\darne\Desktop\DiscordBot-BardGPT\myenv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\darne\Desktop\DiscordBot-BardGPT\bot.py", line 46, in on_ready
    await bot.load_extension(f'cogs.{Filename[:-3]}')
  File "c:\Users\darne\Desktop\DiscordBot-BardGPT\myenv\lib\site-packages\discord\ext\commands\bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "c:\Users\darne\Desktop\DiscordBot-BardGPT\myenv\lib\site-packages\discord\ext\commands\bot.py", line 938, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.event' raised an error: Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

**Comment by FuseFairy** [comment]
You can find the solution here, but the method will still be wrong after a while, and there is no better method for the time being.

https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_FAQ.md
