### ISSUE TITLE
Error while set chatbot: SNlM0e value not found.

### ISSUE THREAD

**Issue by Aftab-Shaikh-op** [FuseFairy/DiscordBot-BardGPT#9]
Hey there FuseFairy, could you please check the following error for me? I'm having this error when I try to set bard cookies.

2023-09-04 14:15:17 ERROR    src.setChatbot -> Error while set chatbot: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

Traceback (most recent call last):
  File "/bot/src/setChatbot.py", line 56, in set_personal_chatbot
    users_chatbot[user_id] = UserChatbot(session_id)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/bot/src/setChatbot.py", line 31, in __init__
    self.chatbot = Bard(token=session_id)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bardapi/core.py", line 55, in __init__
    self.SNlM0e = self._get_snim0e()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bardapi/core.py", line 128, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

I tried to do it with prefix and slash commands both but I do not seem to get any different results. The __Secure-1PSID is unlikely to be invalid because I dropped it straight from the Developer tools.

**Comment by FuseFairy** [comment]
The follow solution may solve the problem.

![image](https://github.com/FuseFairy/DiscordBot-BardGPT/assets/78064680/0814f8bd-2d4a-4f30-9ea6-6acb3338fcae)

**Comment by Aftab-Shaikh-op** [comment]
thank you for the quick reply, it worked!
